%YAML:1.0

cam0:
  T_imu_cam: #rotation from camera to IMU, position of IMU in camera
    - [-0.99997806, -0.00600501,  0.0027968,   0.03847796]
    - [0.00601449, -0.99997615,  0.00339343, -0.0045601]
    - [0.00277635,  0.00341018,  0.99999033,  0.00418038]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [-0.292031518680717,0.08753155838496009,0.0009568457669165753,2.3463489813256424e-05]
  distortion_model: radtan
  intrinsics: [470.0502737897896,468.7574814232544,405.80799445368035,245.2879780490104] #fu, fv, cu, cv
  resolution: [752, 480]
  rostopic: /cam0/image_raw
cam1:
  T_imu_cam: #rotation from camera to IMU, position of IMU in camera
    - [-0.99984421, -0.00389232,  0.01721638, -0.07075565]
    - [0.00394176, -0.9999882,   0.0028389,  -0.00418534]
    - [0.01720512,  0.00290632,  0.99984776,  0.00388861]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [-0.2847596229068525,0.07908861097045865,0.0011071433505703875,0.0005094909873658998]
  distortion_model: radtan
  intrinsics: [472.98384780424163,471.9917417027018,382.1928744696835,268.2536666120421] #fu, fv, cu, cv
  resolution: [752, 480]
  rostopic: /cam1/image_raw