%YAML:1.0 # need to specify the file type at the top!

cam0:
  T_cam_imu:
    - - -0.04030123999740945
      - -0.9989998755524683
      - 0.01936643232049068
      - 0.02103955032447366
    - - 0.026311325355146964
      - -0.020436499663524704
      - -0.9994448777394171
      - -0.038224929976612206
    - - 0.9988410905708309
      - -0.0397693113802049
      - 0.027108627033059024
      - -0.1363488241088845
    - - 0.0
      - 0.0
      - 0.0
      - 1.0
  cam_overlaps:
    - 1
  camera_model: pinhole
  distortion_coeffs:
    - 0.006896928127777268
    - -0.009144207062654397
    - 0.000254113977103925
    - 0.0021434982252719545
  distortion_model: radtan
  intrinsics:
    - 380.9229090195708
    - 380.29264802262736
    - 324.68121181846755
    - 224.6741321466431
  resolution:
    - 640
    - 480
  rostopic: /camera/infra1/image_rect_raw
  timeshift_cam_imu: -0.029958533056650416
cam1:
  T_cam_imu:
    - - -0.03905752472566068
      - -0.9990498568899562
      - 0.019336318430946575
      - -0.02909273113160158
    - - 0.025035478432625047
      - -0.020323396666370924
      - -0.9994799569614147
      - -0.03811090793611019
    - - 0.99892328763622
      - -0.03855311914877835
      - 0.02580547271309183
      - -0.13656684822705098
    - - 0.0
      - 0.0
      - 0.0
      - 1.0
  T_cn_cnm1:
    - - 0.9999992248836708
      - 6.384241340452582e-05
      - 0.0012434452955667624
      - -0.049960282472300055
    - - -6.225102643531651e-05
      - 0.9999991790958949
      - -0.0012798173093508036
      - -5.920119010064575e-05
    - - -0.001243525981443161
      - 0.0012797389115975439
      - 0.9999984079544582
      - -0.00014316003395349448
    - - 0.0
      - 0.0
      - 0.0
      - 1.0
  cam_overlaps:
    - 0
  camera_model: pinhole
  distortion_coeffs:
    - 0.007044055287844759
    - -0.010251485722185347
    - 0.0006674304399871926
    - 0.001678899816379666
  distortion_model: radtan
  intrinsics:
    - 380.95187095303424
    - 380.3065956074995
    - 324.0678433553536
    - 225.9586983198407
  resolution:
    - 640
    - 480
  rostopic: /camera/infra2/image_rect_raw
  timeshift_cam_imu: -0.030340187355085417