%YAML:1.0 # need to specify the file type at the top!

cam0:
  T_cam_imu: #rotation from IMU to camera, position of camera in IMU
    - [-0.9995250378696743, 0.029615343885863205, -0.008522328211654736, 0.04727988224914392]
    - [0.0075019185074052044, -0.03439736061393144, -0.9993800792498829, -0.047443232143367084]
    - [-0.02989013031643309, -0.998969345370175, 0.03415885127385616, -0.0681999605066297]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [0.0034823894022493434, 0.0007150348452162257, -0.0020532361418706202, 0.00020293673591811182]
  distortion_model: equidistant
  intrinsics: [190.97847715128717, 190.9733070521226, 254.93170605935475, 256.8974428996504]
  resolution: [512, 512]
  rostopic: /cam0/image_raw


cam1:
  T_cam_imu: #rotation from IMU to camera, position of camera in IMU
    - [-0.9995110484978581, 0.030299116376600627, -0.0077218830287333565, -0.053697434688869734]
    - [0.008104079263822521, 0.012511643720192351, -0.9998888851620987, -0.046131737923635924]
    - [-0.030199136245891378, -0.9994625667418545, -0.012751072573940885, -0.07149261284195751]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [0.0034003170790442797, 0.001766278153469831, -0.00266312569781606, 0.0003299517423931039]
  distortion_model: equidistant
  intrinsics: [190.44236969414825, 190.4344384721956, 252.59949716835982, 254.91723064636983]
  resolution: [512, 512]
  rostopic: /cam1/image_raw