%YAML:1.0

imu0:
  T_i_b:
    - [1.0, 0.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0, 0.0]
    - [0.0, 0.0, 1.0, 0.0]
    - [0.0, 0.0, 0.0, 1.0]
  accelerometer_noise_density: 0.00207649074
  accelerometer_random_walk: 0.00041327852
  gyroscope_noise_density: 0.00020544166
  gyroscope_random_walk: 1.110622e-05
  model: calibrated
  rostopic: /d455/imu
  time_offset: 0.0
  update_rate: 400
