%YAML:1.0

cam0:
  T_imu_cam:
    - [0.006708021451800439, 0.002425643641803532, 0.9999745590269407, 0.05098782892861867]
    - [0.9999264200621176, 0.010091197021688258, -0.00673217679702115, 0.04586422589354697]
    - [-0.01010727015365992, 0.9999461405473755, -0.0023577731969991467, -0.012631813183337478]
    - [0.0, 0.0, 0.0, 1.0]
  
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [-0.03696737352869157, -0.008917880497032812, 0.008912969593422046, -0.0037685977496087313]
  distortion_model: equidistant
  intrinsics: [351.31400364193297, 351.4911744656785, 367.8522793375995, 253.8402144980996]
  resolution: [720, 540]
  rostopic: "/alphasense/cam0/image_raw"
  timeshift_cam_imu: 0.0019071204237431304

cam1:
  T_imu_cam:
    - [0.0016556126470597954, 0.0009350089535379302, 0.9999981923508761, 0.05050835847481363]
    - [0.9999840642813064, 0.005395690615039778, -0.0016606342845620903, -0.06262779955244471]
    - [-0.005397233569448934, 0.9999850060281122, -0.0009260608798763448, -0.01343471252962214]
    - [0.0, 0.0, 0.0, 1.0]
  
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [-0.039086652082708805, -0.005525347047415151, 0.004398151558986798, -0.0019701263170917808]
  distortion_model: equidistant
  intrinsics: [352.6489794433894, 352.8586498571586, 347.8170010310082, 270.5806692485468]
  resolution: [720, 540]
  rostopic: "/alphasense/cam1/image_raw"
  timeshift_cam_imu: 0.001901867458041627