%YAML:1.0 # need to specify the file type at the top!

cam0:
  T_cam_imu:
    - [-0.011971871166626097, -0.9999224527839351, -0.0034296821033545366, 0.015502382038955003]
    - [-0.013432448816749543, 0.0035904405462792166, -0.9999033343556117, 0.002083766077365473]
    - [0.9998381087053825, -0.011924644868674172, -0.013474391459390306, -0.024349970215062976]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [-0.17360807033873157, 0.02599637863237943, -0.0004062002021667953, 0.00020421105539956608]
  distortion_model: radtan
  intrinsics: [348.9405723835269, 349.17222249380876, 317.9500057518461, 191.53105236987503]
  resolution: [640, 360]
  rostopic: /zedm/zed_node/left_raw/image_raw_gray
  timeshift_cam_imu: 0.004487813209888025

cam1:
  T_cam_imu:
    - [-0.01065171075617588, -0.9999378597093138, -0.0032890390577658413, -0.047516910078538]
    - [-0.0098760688230905, 0.00339426765450343, -0.9999454696190644, 0.0018122086286373555]
    - [0.9998944965958001, -0.01061864713823435, -0.009911609878587802, -0.024894289640368602]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [-0.1731190259160114, 0.024950572238493708, -0.0006423557301684838, -4.4176966247772696e-05]
  distortion_model: radtan
  intrinsics: [349.2518888172092, 349.11028285164315, 322.565825512766, 177.6719980356266]
  resolution: [640, 360]
  rostopic: /zedm/zed_node/right_raw/image_raw_gray
  timeshift_cam_imu: 0.00401158299448889

